//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAcademicQulDtl
    {
        public int AcademicQulDtlID { get; set; }
        public Nullable<int> RegID { get; set; }
        public Nullable<decimal> GetNumbers { get; set; }
        public Nullable<int> QualificationID { get; set; }
        public string PassedYear { get; set; }
    }
}
