//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmission
    {
        public tblAdmission()
        {
            this.tblDefineFeesStudentDtl = new HashSet<tblDefineFeesStudentDtl>();
            this.tblFeesReceiveMst = new HashSet<tblFeesReceiveMst>();
            this.tblGenerateFeesDtl = new HashSet<tblGenerateFeesDtl>();
        }
    
        public int AdmissionID { get; set; }
        public string GRNo { get; set; }
        public Nullable<int> RegID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string RollNoGenerated { get; set; }
        public string Remarks { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string ChallanNoGenerated { get; set; }
        public Nullable<int> ChallanNo { get; set; }
        public Nullable<bool> Hostel { get; set; }
    
        public virtual tblBank tblBank { get; set; }
        public virtual tblDiscount tblDiscount { get; set; }
        public virtual tblStudentRegMst tblStudentRegMst { get; set; }
        public virtual ICollection<tblDefineFeesStudentDtl> tblDefineFeesStudentDtl { get; set; }
        public virtual ICollection<tblFeesReceiveMst> tblFeesReceiveMst { get; set; }
        public virtual ICollection<tblGenerateFeesDtl> tblGenerateFeesDtl { get; set; }
    }
}
