//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountsOBDtl
    {
        public long AccOBDtlID { get; set; }
        public Nullable<long> AccOBMstID { get; set; }
        public string AccountCode { get; set; }
        public Nullable<decimal> AccOB { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
    }
}
