//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendanceLog
    {
        public int AttendanceLogID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> EmpAttendanceDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string Status { get; set; }
    }
}
