//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConfiguration
    {
        public int ConfigID { get; set; }
        public Nullable<bool> IsSearchGRNo { get; set; }
        public Nullable<bool> IsGenerateRollNo { get; set; }
        public string AttendanceMachineIP { get; set; }
        public Nullable<int> DefaultPort { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string FeesVoucher { get; set; }
        public Nullable<bool> PrintAlertOnFeesRcv { get; set; }
        public Nullable<bool> IsBrandedSMS { get; set; }
        public string SMSUserID { get; set; }
        public string SMSPasssword { get; set; }
        public string SMSMask { get; set; }
        public Nullable<int> SMSDelayTime { get; set; }
        public Nullable<bool> IsSendSMSforAttendance { get; set; }
        public string StudAttendanceSMS { get; set; }
        public string StudAttendanceSMSInUrdu { get; set; }
        public Nullable<bool> IsSendUrduSMS { get; set; }
        public Nullable<int> TotalMsgChar { get; set; }
        public Nullable<bool> EnableFeesRecDate { get; set; }
        public Nullable<System.DateTime> FromDatePayroll { get; set; }
        public Nullable<System.DateTime> ToDatePayroll { get; set; }
        public Nullable<bool> IsSearchGRNoExam { get; set; }
        public Nullable<bool> DefinePayrollPeriod { get; set; }
        public Nullable<bool> IsSendUrduSMSAbsent { get; set; }
        public string AbsentSMS { get; set; }
        public string AbsentSMSInUrdu { get; set; }
        public Nullable<int> TotalAbsentMsgChar { get; set; }
        public Nullable<bool> IsSendUrduSMSDefaulter { get; set; }
        public string DefaulterSMS { get; set; }
        public string DefaulterSMSInUrdu { get; set; }
        public Nullable<int> TotalDefaulterMsgChar { get; set; }
        public Nullable<bool> IsSearchGRNoInventory { get; set; }
        public Nullable<bool> IsDeductMoreCLWhenLate { get; set; }
        public Nullable<bool> IsDefineTotalDaysForPayroll { get; set; }
        public Nullable<int> TotalDaysForCalculateOneDaySal { get; set; }
        public Nullable<bool> AllotDuplicateRank { get; set; }
        public Nullable<bool> DeductDiscount { get; set; }
        public Nullable<bool> IsSearchGRNoInUrdu { get; set; }
        public Nullable<bool> InActiveDefaulters { get; set; }
        public string StudentListColumns { get; set; }
        public Nullable<bool> IsSearchGRNoInFeesVoucher { get; set; }
    }
}
