//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCashReceiptDtl
    {
        public int CashRecDtlId { get; set; }
        public Nullable<int> CashRecId { get; set; }
        public Nullable<decimal> CurrentAmount { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public Nullable<decimal> BalanceAmount { get; set; }
        public string ShortNarration { get; set; }
        public string AccountCodeDtl { get; set; }
    
        public virtual tblCashReceiptDtl tblCashReceiptDtl1 { get; set; }
        public virtual tblCashReceiptDtl tblCashReceiptDtl2 { get; set; }
    }
}
