//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConObserDtl
    {
        public int ConObsdtlID { get; set; }
        public Nullable<int> StudentsInfoID { get; set; }
        public string Observations { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Days { get; set; }
        public Nullable<decimal> PreparationDays { get; set; }
        public string Remarks { get; set; }
    }
}
