//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefineSalaryDtl
    {
        public int DefineSalaryDtlID { get; set; }
        public Nullable<int> DefineSalaryMstID { get; set; }
        public Nullable<int> AllowanceID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
    }
}
