//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefineFeesStudentDtl
    {
        public int DefineFeesStudentDtlID { get; set; }
        public Nullable<long> DefineFeesStudentID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
    
        public virtual tblAdmission tblAdmission { get; set; }
        public virtual tblDefineFeesStudentMst tblDefineFeesStudentMst { get; set; }
    }
}
