//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDefineFeesStudentMst
    {
        public tblDefineFeesStudentMst()
        {
            this.tblDefineFeesStudentDtl = new HashSet<tblDefineFeesStudentDtl>();
        }
    
        public long DefineFeesStudentID { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> FeesTypeID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> TotalStudents { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual tblClassMst tblClassMst { get; set; }
        public virtual ICollection<tblDefineFeesStudentDtl> tblDefineFeesStudentDtl { get; set; }
        public virtual tblSection tblSection { get; set; }
        public virtual tblStage tblStage { get; set; }
    }
}
