//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscount
    {
        public tblDiscount()
        {
            this.tblAdmission = new HashSet<tblAdmission>();
            this.tblGenerateFeesDtl = new HashSet<tblGenerateFeesDtl>();
        }
    
        public int DiscountID { get; set; }
        public string DiscountCode { get; set; }
        public string DiscountType { get; set; }
        public string DiscountName { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        public virtual ICollection<tblAdmission> tblAdmission { get; set; }
        public virtual ICollection<tblGenerateFeesDtl> tblGenerateFeesDtl { get; set; }
    }
}
