//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeAttendanceDtl
    {
        public long EmpAttendanceDtlID { get; set; }
        public Nullable<long> EmpAttendanceMstID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> EmpAttendanceDate { get; set; }
    }
}
