//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpID { get; set; }
        public string EmpNo { get; set; }
        public string EmpImagePath { get; set; }
        public string EmployeeName { get; set; }
        public string FatherName { get; set; }
        public string EmpNameInUrdu { get; set; }
        public string FatherNameInUrdu { get; set; }
        public string NIC { get; set; }
        public string Other { get; set; }
        public string Address { get; set; }
        public string Reference { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public byte[] LOGO { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExpDate { get; set; }
        public string NICFrontPath { get; set; }
        public byte[] NICFrontImage { get; set; }
        public string NICBackPath { get; set; }
        public byte[] NICBackImage { get; set; }
        public string LicenseFrontPath { get; set; }
        public byte[] LicenseFrontImage { get; set; }
        public string LicenseBackPath { get; set; }
        public byte[] LicenseBackImage { get; set; }
        public Nullable<System.DateTime> NICExpDate { get; set; }
        public Nullable<int> AllowCLInMonth { get; set; }
        public Nullable<System.TimeSpan> JobStartTime { get; set; }
        public Nullable<System.TimeSpan> JobEndTime { get; set; }
        public Nullable<System.TimeSpan> EmpLateTime { get; set; }
        public Nullable<bool> SaturdayOff { get; set; }
        public Nullable<bool> IsVisitor { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> ResigningDate { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> TotalCL { get; set; }
        public Nullable<int> TotalSickLeaves { get; set; }
        public Nullable<int> AllowSickLeavesInMonth { get; set; }
    }
}
