//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamResultDtl
    {
        public int ExamResultDtlID { get; set; }
        public Nullable<int> ExamResultMstID { get; set; }
        public Nullable<decimal> MarksObtained { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }
    }
}
