//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeesType
    {
        public tblFeesType()
        {
            this.tblDefineFeesDtl = new HashSet<tblDefineFeesDtl>();
            this.tblGenerateFeesDtl = new HashSet<tblGenerateFeesDtl>();
        }
    
        public int FeesTypeID { get; set; }
        public string FeesType { get; set; }
        public string FeesTypeInUrdu { get; set; }
        public Nullable<decimal> FeesAmount { get; set; }
        public string ChargeFee { get; set; }
        public Nullable<bool> DiscountAble { get; set; }
        public Nullable<bool> RefundAble { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SchoolID { get; set; }
    
        public virtual ICollection<tblDefineFeesDtl> tblDefineFeesDtl { get; set; }
        public virtual ICollection<tblGenerateFeesDtl> tblGenerateFeesDtl { get; set; }
    }
}
