//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeesPayDtl
    {
        public long FeesPayDtlID { get; set; }
        public Nullable<long> FeesPayMstID { get; set; }
        public Nullable<int> GenFeesDtlID { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string Status { get; set; }
    }
}
