//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGenerateSalaryDtl
    {
        public int GenSalaryDtlID { get; set; }
        public Nullable<int> GenSalaryMstID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> TotalSalary { get; set; }
        public Nullable<decimal> Fine { get; set; }
        public Nullable<decimal> OneDaySalary { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public Nullable<decimal> Loan { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<decimal> PaidInstallmentAmount { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> PaidAdvance { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<decimal> TotalAllowances { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeductCL { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<int> SickLeaves { get; set; }
        public Nullable<int> Lates { get; set; }
        public Nullable<int> HalfDays { get; set; }
        public Nullable<decimal> ActualSalary { get; set; }
    }
}
