//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManualSalaryPayDtl
    {
        public int ManualSalaryPayDtlID { get; set; }
        public Nullable<int> ManualSalaryPayMstID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> GenSalaryDtlID { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> TotalAllowances { get; set; }
        public Nullable<decimal> NetSalary { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
