//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOpeningQtyDtl
    {
        public long OQDtlID { get; set; }
        public Nullable<long> OQMstID { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> CurrentQty { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
    }
}
