//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParaDtl
    {
        public int ParaDtlID { get; set; }
        public Nullable<int> StudentsInfoID { get; set; }
        public Nullable<int> ParaID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalDays { get; set; }
        public Nullable<decimal> TotalLessons { get; set; }
    }
}
