//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRights
    {
        public long RightID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsSave { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsUpdate { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsRestore { get; set; }
    }
}
