//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentRegMst
    {
        public tblStudentRegMst()
        {
            this.tblAdmission = new HashSet<tblAdmission>();
        }
    
        public int RegID { get; set; }
        public string RegNo { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantNameInUrdu { get; set; }
        public string FatherNameInUrdu { get; set; }
        public string AddressInUrdu { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ImagePath { get; set; }
        public byte[] LOGO { get; set; }
        public Nullable<int> StageID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> DarsgahID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string BloodGroup { get; set; }
        public string BFormNo { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string TemporaryAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string FatherName { get; set; }
        public string FatherNIC { get; set; }
        public string FatherMobileNo { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherQualification { get; set; }
        public Nullable<decimal> FatherMonthlySalary { get; set; }
        public string FatherOfficeAddress { get; set; }
        public string FatherOfficePhoneNo { get; set; }
        public string MotherName { get; set; }
        public string MotherNIC { get; set; }
        public string MotherMobileNo { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherQualification { get; set; }
        public Nullable<decimal> MotherMonthlySalary { get; set; }
        public string MotherOfficeAddress { get; set; }
        public string MotherOfficePhoneNo { get; set; }
        public string DeleteBy { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsAdmit { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string GardianName { get; set; }
        public string LastClassAttended { get; set; }
        public string LastSchoolAttended { get; set; }
        public string NativeLang { get; set; }
        public string RelationtoStu { get; set; }
        public string NameofSignatory { get; set; }
        public Nullable<bool> IsSendMsgtoFather { get; set; }
        public Nullable<bool> IsSendMsgtoMother { get; set; }
        public string PortalID { get; set; }
        public Nullable<System.DateTime> DateOfAdmission { get; set; }
        public Nullable<System.DateTime> DateOfRemoval { get; set; }
        public string ClassAtTimeOfRemoval { get; set; }
        public string CauseOfRemoval { get; set; }
    
        public virtual ICollection<tblAdmission> tblAdmission { get; set; }
        public virtual tblArea tblArea { get; set; }
        public virtual tblCity tblCity { get; set; }
        public virtual tblClassMst tblClassMst { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblProvince tblProvince { get; set; }
        public virtual tblReligion tblReligion { get; set; }
        public virtual tblSection tblSection { get; set; }
        public virtual tblStage tblStage { get; set; }
    }
}
