//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoice2Dtl
    {
        public long SI2DtlID { get; set; }
        public Nullable<long> SI2MstID { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> DiscountPerc { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> CogsAmount { get; set; }
        public Nullable<decimal> CurrentQty { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> GrossAmount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
    }
}
