//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockBalance
    {
        public long TransactionID { get; set; }
        public long ProductID { get; set; }
        public Nullable<int> CusVenID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Packing { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public string TransactionType { get; set; }
        public string QtyType { get; set; }
        public string RefCode { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string StockType { get; set; }
        public Nullable<System.DateTime> TransactionDateTime { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<decimal> TotalInvDisc { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> CogsAmount { get; set; }
        public string Brand { get; set; }
    }
}
