//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTranToClassDtl
    {
        public int TranToClassDtlID { get; set; }
        public Nullable<int> TranClassMstID { get; set; }
        public Nullable<int> AdmissionID { get; set; }
        public string RollNoGenerated { get; set; }
        public string ChallanNoGenerated { get; set; }
    }
}
