//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public int VendorId { get; set; }
        public string VendorAlias { get; set; }
        public string VendorName { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Ph { get; set; }
        public string Saluation { get; set; }
        public string Fax { get; set; }
        public string AltPh { get; set; }
        public string AltContact { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string ShipFromAddress { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public string AccountCode { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> OpBal { get; set; }
        public Nullable<System.DateTime> OpBalDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
