//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vu_ChartOfAccounts
    {
        public int TransactionID { get; set; }
        public string AccountCode { get; set; }
        public string AccountName { get; set; }
        public string AccountType { get; set; }
        public string Description { get; set; }
        public string AccountShortName { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<bool> Normal { get; set; }
        public Nullable<bool> Bank { get; set; }
        public Nullable<bool> Cash { get; set; }
        public string TransactionType { get; set; }
    }
}
