//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vu_RefundableFees
    {
        public long TransactionID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string RefCode { get; set; }
        public Nullable<int> AdmissionID { get; set; }
        public string ApplicantName { get; set; }
        public string FatherName { get; set; }
        public string RollNoGenerated { get; set; }
        public string GRNo { get; set; }
        public Nullable<int> StageID { get; set; }
        public string StageName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> FeesTypeID { get; set; }
        public string FeesType { get; set; }
        public Nullable<int> ChallanNo { get; set; }
        public string ChallanNoGenerated { get; set; }
        public Nullable<int> ClassSessionID { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public string DiscountName { get; set; }
        public Nullable<decimal> FeesAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> EditedDiscAmount { get; set; }
        public Nullable<decimal> NetFees { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> FeesDate { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string TransactionType { get; set; }
        public int GenFeesDtlID { get; set; }
    }
}
