//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vu_SickLeaves
    {
        public int TransactionID { get; set; }
        public Nullable<int> SickLeaves { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> EmpID { get; set; }
    }
}
