//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vu_StudentsList
    {
        public int RegID { get; set; }
        public string RegNo { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantNameInUrdu { get; set; }
        public Nullable<decimal> Age { get; set; }
        public string BFormNo { get; set; }
        public string DateOfBirth { get; set; }
        public string FatherMobileNo { get; set; }
        public string FatherNIC { get; set; }
        public string FatherName { get; set; }
        public string FatherNameInUrdu { get; set; }
        public string Gender { get; set; }
        public string DateOfRemoval { get; set; }
        public string CauseOfRemoval { get; set; }
        public string NativeLang { get; set; }
        public string TemporaryAddress { get; set; }
        public string MotherMobileNo { get; set; }
        public string MotherNIC { get; set; }
        public string MotherName { get; set; }
        public string PermanentAddress { get; set; }
        public string PhoneNo { get; set; }
        public string DateOfAdmission { get; set; }
        public Nullable<int> DarsgahID { get; set; }
        public Nullable<int> StageID { get; set; }
        public string StageName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SectionID { get; set; }
        public string SectionName { get; set; }
        public string ChallanNoGenerated { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string RollNoGenerated { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int AdmissionID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string GRNo { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Darsgah { get; set; }
    }
}
